spring:
  h2.console.enabled: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
  jackson.deserialization:
    FAIL_ON_UNKNOWN_PROPERTIES: false
  main.banner-mode: off
