name: Test CI
on:
  push:
    branches:
      - master

jobs:
  TEST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🪜 Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica

      - name: 🔦 TEST
        run: |
          chmod +x ./gradlew
          ./gradlew test
